initApiData:
    uri: /api/init/data
    controller: Controller\api\InitController
    httpMethod: [GET]
initApiSchema:
    uri: /api/init/schema
    controller: Controller\api\SchemaController
    httpMethod: [GET]
doc:
    uri: /doc
    controller: Controller\DocController
    httpMethod: [GET]
getStations:
    uri: /api/stations
    controller: Controller\api\Station\StationsController
    httpMethod: [GET]
getStationById:
    uri: '/api/station/{id}'
    controller: Controller\api\Station\StationIdController
    httpMethod: [GET]
getStationStatusById:
    uri: '/api/station/{id}/status[/{optional}]'
    controller: Controller\api\Station\StationStatusIdController
    httpMethod: [GET]
getStationsStatus:
    uri: /api/stations/status
    controller: Controller\api\Status\StationsStatusController
    httpMethod: [GET]
getVelos:
    uri: /api/velos
    controller: Controller\api\Velo\VeloController
    httpMethod: [GET]
getVeloById:
    uri: /api/velo/{id}
    controller: Controller\api\Velo\VeloByIdController
    httpMethod: [GET]
getVeloLocById:
    uri: /api/velo/{id}/location
    controller: Controller\api\Velo\VeloLocByIdController
    httpMethod: [PUT]
getVeloRestoreById:
    uri: /api/velo/{velo_id}/restore/{station_id}
    controller: Controller\api\Velo\VeloRestoreByIdController
    httpMethod: [PUT]
home:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]
